### ISSUE TITLE
Space before comma

### ISSUE THREAD

**Issue by gregsexton** [b4winckler/vim-angry#1]
Hi,

Just seen this new repo in my feed. This handles many more use cases than [argtextobj](http://www.vim.org/scripts/script.php?script_id=2699). I'm an instant convert!

Just thought I'd bring to your attention a possible bug.

Place your cursor on the 'b' of 'bar' and issue `daa`.

```
function(foo, bar , baz)
```

You get this:

```
function(foo , baz)
```

Notice the space after 'foo'. Is this intentional behaviour?

Many thanks,

Greg

**Comment by b4winckler** [comment]
A first issue - that was quick!  Great!

The behavior you describe is (more or less) by design.  It turns out to be very difficult to cater to all possible styles of writing arguments (multiline arguments, comma before argument [common in Haskell], comments before/after argument, ...).  To work around some of these problem there are two versions of each operator -- the default eats the comma in front of the argument and the alternate eats the comma after the argument.

In this case the alternate operator `daA` will do the trick.

By the way, I also looked around thinking surely there must already be a plugin that works.  However, I couldn't find one that even did the basics right so I started my own.  I'm intent on getting this to work as well as is possible so please let me know if you find some other strange behavior and I'll try to fix it.

**Comment by gregsexton** [comment]
Hi,

Thanks for your response and sorry for raising an issue so quickly after you released this! :)

Yes, `daA` works. Thanks for explaining the difference between `daa` and `daA`. I now have a much better understanding.

I will certainly look out and report anything odd I find. As you say, nothing out there seems to do this well so I'm very pleased to find this plugin. The fact that it handles arguments on their own line has solved my biggest grievance with other plugins.

Thanks,

Greg

**Comment by b4winckler** [comment]
I don't mind the issue report.  On the contrary, it is nice that somebody likes it. :)

I updated the README to hopefully be a bit clearer on the difference between `aa` and `aA`.
